# Generated by Django 5.1.1 on 2024-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=30)),
                ('sku', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'verbose_name_plural': 'Area 1',
            },
        ),
        migrations.CreateModel(
            name='area2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=30)),
                ('sku', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'verbose_name_plural': 'Area 2',
            },
        ),
        migrations.CreateModel(
            name='area3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=30)),
                ('sku', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'verbose_name_plural': 'Area 3',
            },
        ),
        migrations.CreateModel(
            name='area4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=30)),
                ('sku', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'verbose_name_plural': 'Area 4',
            },
        ),
        migrations.CreateModel(
            name='area5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=30)),
                ('sku', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'verbose_name_plural': 'Area 5',
            },
        ),
        migrations.CreateModel(
            name='inventario1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('colaborador', models.IntegerField(verbose_name='Numero de colaborador')),
                ('fecha', models.DateField()),
                ('sku', models.ManyToManyField(to='Muebles.area1')),
            ],
            options={
                'verbose_name_plural': 'Inventario Area 1',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='inventario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('colaborador', models.IntegerField(verbose_name='Numero de colaborador')),
                ('fecha', models.DateField()),
                ('sku', models.ManyToManyField(to='Muebles.area2')),
            ],
            options={
                'verbose_name_plural': 'Inventario Area 2',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='inventario3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('colaborador', models.IntegerField(verbose_name='Numero de colaborador')),
                ('fecha', models.DateField()),
                ('sku', models.ManyToManyField(to='Muebles.area3')),
            ],
            options={
                'verbose_name_plural': 'Inventario Area 3',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='inventario4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('colaborador', models.IntegerField(verbose_name='Numero de colaborador')),
                ('fecha', models.DateField()),
                ('sku', models.ManyToManyField(to='Muebles.area4')),
            ],
            options={
                'verbose_name_plural': 'Inventario Area 4',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='inventario5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('colaborador', models.IntegerField(verbose_name='Numero de colaborador')),
                ('fecha', models.DateField()),
                ('sku', models.ManyToManyField(to='Muebles.area5')),
            ],
            options={
                'verbose_name_plural': 'Inventario Area 5',
                'ordering': ['-fecha'],
            },
        ),
    ]
